### ISSUE TITLE
Please also via xml

### ISSUE THREAD

**Issue by Rainer-Lang** [KasualBusiness/MaterialNumberPicker#5] opened 2015-11-06 17:49 UTC
Really great lib!

**Comment by StephenVinouze** [comment] 2015-11-09 13:12
Duplicate of #4

**Comment by Rainer-Lang** [comment] 2015-11-15 08:55
Is it possible to use the extra styling and methods via xml? Would be helpful.

**Comment by StephenVinouze** [comment] 2015-11-15 10:55
I could look into it. Should not be a problem ;)

**Comment by StephenVinouze** [comment] 2015-11-20 11:28
I just released a newer version (1.2.0) that supports XML for each attributes. That should let you use this library any way you prefer (XML or programmatically) ;)

**Closed as completed by StephenVinouze** 2015-11-20 11:28 UTC

**Comment by Rainer-Lang** [comment] 2015-11-20 17:52
@StephenVinouze Thanks a lot. I will try it.
Awesome! :-)
